version: '3.8'

services:
  cadastro-produtos-design-patterns:
    image: ${DOCKER_REGISTRY-}cadastroprodutosdesignpatterns
    build:
      context: .
      dockerfile: cadastro-produtos-design-patterns/Dockerfile
    depends_on: 
    - db
    environment:
    - ConnectionStrings__DefaultConnection=Server=db,1433;Database=db_ecommerce;User Id=sa;Password=SenhaForte@123;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "cLU116+`y]3"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata:
